### PR TITLE
update repository details to new organisation

### PR DESCRIPTION
**Pull request by Dylan-DPC**
- [x] I have created tests for any new feature, or added regression tests for bugfixes.
- [x] `cargo test` succeeds
- [x] Clippy is happy: `cargo +nightly clippy` succeeds
- [x] Rustfmt is happy: `cargo +nightly fmt` succeeds
(all checks not needed)

### CODE REVIEW

**Comment by epage** [comment]
(let's see if bors is setup)

**Comment by killercup** [comment]
bors ping

**Comment by killercup** [comment]
hi, bors! 👋 

bors r+

**Pull request merged**
