### PR TITLE
Change tempdir to tempfile in readme

### LINKED ISSUE #88: Update readme to point to tempfile rather than tempdir
tempdir is being merged into tempfile, see https://github.com/rust-lang-nursery/tempdir/issues/45

### PR DESCRIPTION
**Pull request by Dylan-DPC**
- [n/A] I have created tests for any new feature, or added regression tests for bugfixes.
- [n/A] `cargo test` succeeds
- [n/A] Clippy is happy: `cargo +nightly clippy` succeeds
- [n/A] Rustfmt is happy: `cargo +nightly fmt` succeeds

Closes #88

### CODE REVIEW

**Comment by epage** [comment]
@killercup looks like I need permission again to do reviews.

**Comment by killercup** [comment]
What's wrong with tempdir?

(re-added you, @epage. bors seems to have not migrated the permissions with the github transfer)

**Comment by epage** [comment]
> What's wrong with tempdir? Is the migration to tempfile something that's happening ecosystem-wide?

it looks like tempdir is being merged into tempfile
See https://github.com/rust-lang-nursery/tempdir/issues/45

**Comment by epage** [comment]
Oh, looks like the merge might not be complete

> I was hoping we could wait until there's a published version of tempfile folks can immediately get before we do though.

> @Stebalien do you have a plan in mind for the next release of tempfile? It would need to be a 3.0.0 wouldn't it, unless we go back and deprecate/shim the changed APIs on NamedTempFile.

And https://github.com/Stebalien/tempfile/issues/43 for tempfile's merge

**Comment by Dylan-DPC** [comment]
Yes it isn't complete but it is fine to people to it from the start. We are just suggesting the crate so it doesn't harm anyone even though it hasn't been merged yet :stuck_out_tongue: .

**Comment by epage** [comment]
Since this is just about recommending and not use, its probably fine to eagerly advertise tempfile.

bors r+

**Pull request merged**
